metadata:
  name: wit-db
  labels:
    service: wit-db
  annotations:
    configmap.fabric8.io/update-on-change: "wit"
spec:
  replicas: 1
  selector:
    service: wit-db
  template:
    metadata:
      labels:
        service: wit-db
    spec:
      containers:
      - name: wit-db
        image: registry.centos.org/postgresql/postgresql:9.6
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRESQL_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wit
              key: db.password
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 60
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - exec pg_isready --host $POD_IP
          initialDelaySeconds: 20
          timeoutSeconds: 3
          periodSeconds: 5
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/pgsql
          name: wit-postgresql-data
          readOnly: false
      volumes:
      - name: wit-postgresql-data
        persistentVolumeClaim:
          claimName: wit-postgresql-data