metadata:
  annotations:
    configmap.fabric8.io/update-on-change: "fabric8"
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        fabric8.io/service-dependencies: "f8tenant,auth,wit"
        pod.beta.kubernetes.io/init-containers: |- 
          [
          {
            "name": "wait-for-f8tenant",
            "image": "fabric8/fabric8-dependency-wait-service:${dependency-wait-service.version}",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sh", "-c", "fabric8-dependency-wait-service-linux-amd64 http://f8tenant:80/api/status"],
            "env": [{
              "name": "DEPENDENCY_POLL_INTERVAL",
              "value": "1"
            }, {
              "name": "DEPENDENCY_LOG_VERBOSE",
              "value": "true"
            }]
          },
          {
            "name": "wait-for-auth",
            "image": "fabric8/fabric8-dependency-wait-service:${dependency-wait-service.version}",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sh", "-c", "fabric8-dependency-wait-service-linux-amd64 http://auth:80/api/status"],
            "env": [{
              "name": "DEPENDENCY_POLL_INTERVAL",
              "value": "1"
            }, {
              "name": "DEPENDENCY_LOG_VERBOSE",
              "value": "true"
            }]
          },
          {
            "name": "wait-for-wit",
            "image": "fabric8/fabric8-dependency-wait-service:${dependency-wait-service.version}",
            "imagePullPolicy": "IfNotPresent",
            "command": ["sh", "-c", "fabric8-dependency-wait-service-linux-amd64 http://wit:80/api/status"],
            "env": [{
              "name": "DEPENDENCY_POLL_INTERVAL",
              "value": "1"
            }, {
              "name": "DEPENDENCY_LOG_VERBOSE",
              "value": "true"
            }]
          }
          ]
    spec:
      containers:
      - image: "fabric8/fabric8-ui:${fabric8-ui.version}"
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 20
          timeoutSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          timeoutSeconds: 10
        env:
        - name: "KUBERNETES_MODE"
          value: "true"
        - name: "BRANDING"
          value: "fabric8"
        - name: "K8S_API_SERVER"
          valueFrom:
            configMapKeyRef:
              name: fabric8
              key: apiserver.host
        - name: "WS_K8S_API_SERVER"
          valueFrom:
            configMapKeyRef:
              name: fabric8
              key: apiserver.host
        - name: "FABRIC8_SSO_API_URL"
          valueFrom:
            configMapKeyRef:
              name: sso
              key: keycloak.url
        - name: "FABRIC8_WIT_API_URL"
          valueFrom:
            configMapKeyRef:
              name: fabric8
              key: wit.api.url
        - name: "FABRIC8_TENANT_API_URL"
          valueFrom:
            configMapKeyRef:
              name: fabric8
              key: f8tenant.api.url
        - name: "FABRIC8_FORGE_API_URL"
          valueFrom:
            configMapKeyRef:
              name: fabric8
              key: forge.api.url
        - name: "OPENSHIFT_CONSOLE_URL"
          valueFrom:
            configMapKeyRef:
              name: fabric8
              key: openshift.console.url
        - name: "FABRIC8_RECOMMENDER_API_URL"
          valueFrom:
            configMapKeyRef:
              name: fabric8
              key: recommender.api.url
        - name: "PROXIED_K8S_API_SERVER"
          valueFrom:
            configMapKeyRef:
              name: fabric8
              key: proxy.pass.server
        - name: "PROXY_PASS_URL"
          valueFrom:
            configMapKeyRef:
              name: fabric8
              key: proxy.pass.url
        - name: "K8S_API_SERVER_PROTOCOL"
          valueFrom:
            configMapKeyRef:
              name: fabric8
              key: apiserver.protocol
        - name: "K8S_API_SERVER_BASE_PATH"
          valueFrom:
            configMapKeyRef:
              name: fabric8
              key: apiserver.base.path
        - name: "WS_K8S_API_SERVER_BASE_PATH"
          valueFrom:
            configMapKeyRef:
              name: fabric8
              key: ws.apiserver.base.path
        - name: "WS_K8S_API_SERVER_PROTOCOL"
          valueFrom:
            configMapKeyRef:
              name: fabric8
              key: ws.apiserver.protocol
        - name: "WS_K8S_API_SERVER"
          valueFrom:
            configMapKeyRef:
              name: fabric8
              key: ws.apiserver.host
